# -*- coding: utf-8 -*-
"""agentefloravision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GW7JFvS2TMviZ7Yy4fey7uzNe9MpM1qW

# FloraVision
Agente que recibe el estado de cada flor toma decisiones automáticas, registra historial y genera un reporte al final del día.

## Precio por tipo de flor (editables)
"""

PRECIOS_BASE = {
    "rosa":      50,
    "girasol":   40,
    "margarita": 25,
    "clavel":    30,
    "lirio":     60,
    "orquidea":  120,
    "tulipan":   70,
}

print("Precios base cargados:")
for flor, precio in PRECIOS_BASE.items():
    print(f"   {flor.capitalize()}: RD$ {precio:.2f}") #mayusculas y decimales

"""## Reglas de deterioro y descuentos (editables)"""

REGLAS = [
    ("Fresca",           0.00, 0.30,  0),   #No descuento
    ("Deterioro leve",   0.30, 0.60, 20),   #20% de descuento
    ("Deterioro severo", 0.60, 0.70, 50),   #50% de descuento
    ("Pérdida",          0.70, 1.00, 100),  #No se vende
]

print("Reglas de deterioro cargadas:")
for nombre, minimo, maximo, descuento in REGLAS:
    print(f"   {nombre}: {int(minimo*100)}%-{int(maximo*100)}% deterioro -> {descuento}% descuento") #calcula descuento

"""## Cálculo de precio a partir de lo recibido

"""

#recibe: tipo de flor y probabilidades de la IA
#ej: [0.1, 0.8, 0.1] = [% fresca, % deteriorada, % perdida]

def calcular_precio(tipo_flor, probabilidades):
    tipo_flor = tipo_flor.lower()
    if tipo_flor not in PRECIOS_BASE:
        return None

    precio_base     = PRECIOS_BASE[tipo_flor]
    nivel_deterioro = probabilidades[1] + probabilidades[2]
    estado, descuento = "Pérdida", 100

    for nombre, minimo, maximo, pct in REGLAS:
        if minimo <= nivel_deterioro < maximo:
            estado, descuento = nombre, pct
            break

    precio_final = precio_base * (1 - descuento / 100)

    return {
        "tipo_flor":       tipo_flor.capitalize(),
        "precio_base":     precio_base,
        "nivel_deterioro": nivel_deterioro,
        "estado":          estado,
        "descuento":       descuento,
        "precio_final":    precio_final,
    }

print(" Función calcular_precio() lista.")

"""## Agente Inteligente FloraVision
Agente que va a actuar para gestionar el inventario de flores

"""

import datetime

class AgenteFloraVision:
    """
    Agente inteligente que gestiona el inventario floral.
    Ciclo: Percibir -> Razonar -> Actuar -> Reportar
    """

    def __init__(self):
        self.historial = []
        self.alertas   = []
        print("Agente FloraVision iniciado.")
        print(f"   Fecha: {datetime.date.today()}\n")

    def percibir(self, tipo_flor, probabilidades, cantidad=1):
        """PASO 1: Recibe información de la cámara/IA"""
        resultado = calcular_precio(tipo_flor, probabilidades)
        if resultado is None:
            print(f"Flor '{tipo_flor}' no reconocida.")
            return
        resultado["cantidad"]  = cantidad
        resultado["timestamp"] = datetime.datetime.now().strftime("%H:%M:%S")
        self.razonar(resultado)

    def razonar(self, datos):
        """PASO 2: Evalúa el estado y decide qué hacer"""
        estado = datos["estado"]

        if estado == "Fresca":
            decision = "mantener"
            mensaje  = f"{datos['tipo_flor']} en buen estado. Precio normal: RD$ {datos['precio_final']:.2f}"

        elif estado == "Deterioro leve":
            decision = "descuento"
            mensaje  = (f"{datos['tipo_flor']} con deterioro leve. "
                        f"Descuento {datos['descuento']}% → RD$ {datos['precio_final']:.2f}. Vender hoy.")

        elif estado == "Deterioro severo":
            decision = "descuento_urgente"
            mensaje  = (f"{datos['tipo_flor']} con deterioro severo. "
                        f"Descuento {datos['descuento']}% → RD$ {datos['precio_final']:.2f}. Vender URGENTE.")
            self.alertas.append(f"[{datos['timestamp']}] URGENTE: {datos['tipo_flor']} necesita venderse hoy con 50% descuento.")

        else:
            decision = "retirar"
            mensaje  = f"{datos['tipo_flor']} no apta para venta. Retirar del inventario."
            self.alertas.append(f"[{datos['timestamp']}] PÉRDIDA: {datos['cantidad']} tallo(s) de {datos['tipo_flor']} retirados.")

        datos["decision"] = decision
        datos["mensaje"]  = mensaje
        self.actuar(datos)

    def actuar(self, datos):
        """PASO 3: Ejecuta la decisión y registra en historial"""
        print(f"[{datos['timestamp']}] {datos['mensaje']}")
        self.historial.append(datos)

    def generar_reporte(self):
        """PASO 4: Reporte automático del día"""

        print("        REPORTE DIARIO - FLORAVISION")
        print(f"        Fecha: {datetime.date.today()}")


        if not self.historial:
            print("No se procesaron flores hoy.")
            return

        total_tallos  = sum(f["cantidad"] for f in self.historial)
        perdidas      = [f for f in self.historial if f["decision"] == "retirar"]
        con_descuento = [f for f in self.historial if "descuento" in f["decision"]]
        frescas       = [f for f in self.historial if f["decision"] == "mantener"]

        dinero_perdido     = sum(f["precio_base"] * f["cantidad"] for f in perdidas)
        dinero_recuperable = sum(f["precio_final"] * f["cantidad"] for f in con_descuento)
        dinero_normal      = sum(f["precio_final"] * f["cantidad"] for f in frescas)

        print(f"\n Total de tallos evaluados: {total_tallos}")
        print(f" En buen estado:            {sum(f['cantidad'] for f in frescas)} tallos")
        print(f" Con descuento:             {sum(f['cantidad'] for f in con_descuento)} tallos")
        print(f" Pérdidas:                  {sum(f['cantidad'] for f in perdidas)} tallos")
        print(f"\n Ingresos a precio normal:  RD$ {dinero_normal:.2f}")
        print(f" Ingresos con descuento:    RD$ {dinero_recuperable:.2f}")
        print(f" Pérdidas del día:           RD$ {dinero_perdido:.2f}")
        print(f" Total recuperable hoy:      RD$ {dinero_normal + dinero_recuperable:.2f}")

        if perdidas:
            print(f"\n Flores con más pérdidas hoy:")
            conteo = {}
            for f in perdidas:
                conteo[f["tipo_flor"]] = conteo.get(f["tipo_flor"], 0) + f["cantidad"]
            for flor, cant in sorted(conteo.items(), key=lambda x: -x[1]):
                print(f"   - {flor}: {cant} tallo(s) perdido(s)")

        if self.alertas:
            print(f"\n Alertas generadas hoy ({len(self.alertas)}):")
            for alerta in self.alertas:
                print(f"   {alerta}")


        print(" Reporte completado.")

print(" Clase AgenteFloraVision lista.")

"""## 5. Prueba del agente
Simulación de flores detectadas durante el día.
"""

# Crear el agente
agente = AgenteFloraVision()

print("--- Procesando flores del día ---\n")

# Flores simuladas: (tipo, [prob_fresca, prob_deteriorada, prob_perdida], cantidad)
flores_del_dia = [
    ("rosa",      [0.90, 0.08, 0.02], 10),  # Frescas
    ("rosa",      [0.20, 0.55, 0.25],  5),  # Deterioro severo
    ("girasol",   [0.60, 0.35, 0.05],  8),  # Deterioro leve
    ("margarita", [0.05, 0.10, 0.85],  3),  # Pérdida
    ("clavel",    [0.80, 0.15, 0.05], 12),  # Frescas
    ("lirio",     [0.30, 0.45, 0.25],  6),  # Deterioro leve
    ("tulipan",   [0.10, 0.15, 0.75],  4),  # Pérdida
    ("orquidea",  [0.95, 0.04, 0.01],  2),  # Frescas
]

for tipo, probs, cantidad in flores_del_dia:
    agente.percibir(tipo, probs, cantidad)

"""## 6. Reporte final del día"""

agente.generar_reporte()